### PR TITLE
Pull Request for #10: Implement autofill program

### PR DESCRIPTION
**Pull request by veli-m-andirin**
@rcalvo12, could you please review the changes here? I brought in our autofill program from Protests with some slight improvements and a help file.

@jmshapir, could you please share write permission with @rcalvo12?

(If you think we should ask someone else for review, that is fine with me, too.)

### CODE REVIEW

**Comment by jmshapir** [comment]
@veli-m-andirin thanks! I added @ew487 with read permissions for now. (We can elevate if needed.)

Can you please assign @ew487 as reviewer when @ew487 accepts the invitation to the repository?

Thanks both!

**Comment by veli-m-andirin** [comment]
Thanks @jmshapir! @ew487, could you please review the changes here? Please see the [opening comment](https://github.com/gslab-econ/gslab_stata/pull/11#issue-1303910380), and let me know if you have any questions.

**Review by ew487 — APPROVED** [review]

**Comment by rcalvo12** [comment]
@veli-m-andirin Did you still want my review on this?

**Comment by veli-m-andirin** [comment]
Thanks @rcalvo12! I think one pair of eyes would suffice.

**Comment by veli-m-andirin** [comment]
Summary [here](https://github.com/gslab-econ/gslab_stata/tree/19f7734845917f2d6ad5fe188b8546957141bf55).

**Pull request merged**
